-- AlterTable
ALTER TABLE "Property" ADD COLUMN     "amenities" TEXT[],
ADD COLUMN     "countryCode" TEXT NOT NULL DEFAULT 'ZA',
ADD COLUMN     "features" TEXT[],
ADD COLUMN     "sqmt" DOUBLE PRECISION NOT NULL DEFAULT 0;

-- AlterTable
ALTER TABLE "Unit" ADD COLUMN     "bathrooms" DOUBLE PRECISION NOT NULL DEFAULT 1,
ADD COLUMN     "bedrooms" INTEGER NOT NULL DEFAULT 1,
ADD COLUMN     "deposit" DOUBLE PRECISION NOT NULL DEFAULT 0,
ADD COLUMN     "marketRent" DOUBLE PRECISION NOT NULL DEFAULT 0,
ADD COLUMN     "sqmt" DOUBLE PRECISION NOT NULL DEFAULT 0;
