-- CreateEnum
CREATE TYPE "PropertyFeature" AS ENUM ('ALARM_SYSTEM', 'AIR_CONDITIONING', 'WIFI_INTERNET', 'CABLE_TV', 'DISHWASHER', 'DRYER', 'FRIDGE', 'MICROWAVE', 'OVEN', 'STOVE', 'FIREPLACE');

-- CreateEnum
CREATE TYPE "PropertyAmenity" AS ENUM ('BBQ_GRILL', 'POOL', 'FITNESS_CENTER', 'PET_FRIENDLY', 'GYM', 'LAUNDRY', 'PARKING', 'STORAGE');
